julia:
  name: "julia"
  iters: 40
  c:
    x: -0.7
    y: 0.3
  cmap:
    r_freq: 6
    g_freq: 8
    g_phase: 1
    b_freq: 10
    b_phase: 3

mandelbrot:
  name: "mandelbrot"
  iters: 50
  c:
    x: -0.6
  cmap:
    r_freq: 5
    g_freq: 7
    g_phase: 2
    b_freq: 11
    b_phase: 4

burning_ship:
  name: "burning_ship"
  iters: 40
  c:
    x: -0.4
    y: -0.4
  cmap:
    r_freq: 5
    g_freq: 7
    g_phase: 2
    b_freq: 11
    b_phase: 4

newton:
  name: "newton"
  iters: 30
  cmap:
    r_freq: 6
    g_freq: 8
    g_phase: 1
    b_freq: 10
    b_phase: 3